using RPGDataEditor.Core;
using RPGDataEditor.Wpf.Providers;
using System;
using System.Reflection;
using System.Windows;
using System.Windows.Controls;

namespace RPGDataEditor.Wpf.Controls
{
    public class AutoGeneratedComplexControl : AutoGeneratedControl
    {
        protected override DependencyObject CreateContent()
        {
            if (PropertyContext == null)
            {
                return null;
            }
            DependencyObject root = Root as DependencyObject;
            if (root is Panel panel)
            {
                GenerateAndAddControlsTo(panel, PropertyContext.GetType());
            }
            return root;
        }

        protected virtual void GenerateAndAddControlsTo(Panel panel, Type type)
        {
            PropertyInfo[] properties = type.GetProperties(BindingFlags.Public | BindingFlags.Instance);
            foreach (PropertyInfo property in properties)
            {
                DependencyObject control = LoadControl(property);
                if (control == null)
                {
                    GenerateAndAddControlsTo(panel, property.PropertyType);
                }
                if (control is UIElement element)
                {
                    panel.Children.Add(element);
                }
            }
        }
    }
}
