using RPGDataEditor.Core;
using RPGDataEditor.Wpf.Providers;
using System;
using System.Reflection;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Markup;

namespace RPGDataEditor.Wpf.Controls
{
    [ContentProperty(nameof(Root))]
    public class AutoGeneratedControl : UserControl
    {
        public static DependencyProperty PropertyContextProperty =
            DependencyProperty.Register(nameof(PropertyContext), typeof(object), typeof(AutoGeneratedControl));
        public object PropertyContext {
            get => GetValue(PropertyContextProperty);
            set => SetValue(PropertyContextProperty, value);
        }

        public static DependencyProperty PropertyNameProperty =
            DependencyProperty.Register(nameof(PropertyName), typeof(string), typeof(AutoGeneratedControl));
        public string PropertyName {
            get => (string)GetValue(PropertyNameProperty);
            set => SetValue(PropertyNameProperty, value);
        }

        public static DependencyProperty RootProperty =
            DependencyProperty.Register(nameof(Root), typeof(object), typeof(AutoGeneratedComplexControl));
        public object Root {
            get => GetValue(RootProperty);
            set => SetValue(RootProperty, value);
        }

        protected override void OnInitialized(EventArgs e)
        {
            base.OnInitialized(e);
            if (Content == null)
            {
                Recreate();
            }
            this.AddValueChanged(PropertyContextProperty, OnContextChanged);
            this.AddValueChanged(PropertyNameProperty, OnContextChanged);
            DataContextChanged += OnDataContextChanged;
        }

        private void OnContextChanged(object sender, EventArgs e) => Recreate();

        protected virtual void OnDataContextChanged(object sender, DependencyPropertyChangedEventArgs e) => Recreate();

        protected virtual void Recreate()
        {
            ClearContent();
            Content = CreateContent();
        }

        protected virtual void ClearContent() => Content = null;

        protected virtual DependencyObject CreateContent()
        {
            object context = GetBindingExpression(PropertyContextProperty) != null ? PropertyContext : PropertyContext ?? DataContext;
            if (context == null || string.IsNullOrEmpty(PropertyName))
            {
                return null;
            }
            PropertyInfo property = context.GetType().GetProperty(PropertyName, BindingFlags.Public | BindingFlags.Instance);
            if (property == null)
            {
                return null;
            }
            DependencyObject control = LoadControl(property);
            if (control == null)
            {
                return null;
            }
            if (control is FrameworkElement element)
            {
                element.DataContext = context;
            }
            if (Root is Panel panel)
            {
                panel.Children.Add((UIElement)control);
                return panel;
            }
            return control;
        }

        protected virtual DependencyObject LoadControl(PropertyInfo property)
        {
            IControlGenerateTemplateProvider provider = Application.Current.TryResolve<IControlGenerateTemplateProvider>();
            ControlGenerateTemplate template = provider.Resolve(property.PropertyType);
            return template?.LoadContent(property);
        }
    }
}
